.github/workflows/check.yml
pyproject.toml

Use latest version and test other OSs

---

src/tox_uv/_installer.py

Use uv freeze over pip

---

README.md
pyproject.toml
src/tox_uv/_venv.py
tests/test_tox_uv_installer.py
tox.ini

Disable adding the seed packages by default

---

README.md
pyproject.toml
src/tox_uv/_package.py
src/tox_uv/_run.py
src/tox_uv/plugin.py
tests/test_tox_uv_package.py

Use uv for packaging environments too

---

tests/test_tox_uv_package.py

sdist fixed upstream

---

.github/workflows/check.yml
.github/workflows/release.yml

Use uv in CI over pip

---

pyproject.toml
tests/test_tox_uv_installer.py
tests/test_tox_uv_package.py

Fix CI for 0.1.5

---

src/tox_uv/_venv.py
tests/test_tox_uv_venv.py

Pass through often used environment variables

---

pyproject.toml
src/tox_uv/_installer.py
tests/demo_pkg_inline/build.py
tests/test_tox_uv_package.py

Validate package name of sdist/wheel/editable to be installed

---

.github/workflows/check.yml
.pre-commit-config.yaml
pyproject.toml
src/tox_uv/_venv.py
src/tox_uv/_venv_query.py
tests/test_tox_uv_venv.py
tox.ini

Add PyPy support

---

src/tox_uv/_venv.py

Fix environment check

---

pyproject.toml
src/tox_uv/_venv.py
tests/test_tox_uv_venv.py
tox.ini

Inline uv venv into the tox folder and expose uv to created env

---

.pre-commit-config.yaml
src/tox_uv/_venv.py
tests/test_tox_uv_venv.py

Fix failure when running within a UV venv activated shell

---

pyproject.toml
src/tox_uv/_venv.py
tests/test_tox_uv_venv.py

Skip missing interpreters

---

.github/SECURITY.md
.github/workflows/check.yml
.pre-commit-config.yaml
pyproject.toml
src/tox_uv/_venv.py
tests/test_tox_uv_venv.py

Fix base python conflict

---

.pre-commit-config.yaml
README.md
pyproject.toml
src/tox_uv/_installer.py
src/tox_uv/_run_lock.py
src/tox_uv/_venv.py
src/tox_uv/plugin.py
tests/test_tox_uv_lock.py
tox.ini

Resolves #81 
Requires https://github.com/tox-dev/tox/pull/3347

Add uv lock support

---

README.md

Document lack of deps for uv-venv-lock-runner

---

src/tox_uv/_run_lock.py
tests/test_tox_uv_lock.py

Resolves https://github.com/tox-dev/tox-uv/issues/93

Do not install dev dependencies by default

---

src/tox_uv/_run_lock.py
tests/test_tox_uv_lock.py

Fix uv output shows with no verbose flag

---

README.md
src/tox_uv/_run_lock.py
tests/test_tox_uv_lock.py

Allow passing extra flags to uv sync

---

README.md
src/tox_uv/_run_lock.py
tests/test_tox_uv_lock.py

Fix uv_sync_flags fails in TOML config and add support for dependency_groups

---

README.md
src/tox_uv/_venv.py
tests/test_tox_uv_venv.py

Add support for system_site_packages matching tox own behavior

---

src/tox_uv/_installer.py

Improve naming for logger instance

---

.github/workflows/check.yaml
.pre-commit-config.yaml
pyproject.toml
src/tox_uv/_venv.py
tests/conftest.py
tests/test_tox_uv_lock.py
tests/test_tox_uv_venv.py
tox.ini

Respect UV_PYTHON_PREFERENCE environment variable

---

.pre-commit-config.yaml
pyproject.toml
src/tox_uv/_venv.py
tests/test_tox_uv_venv.py
tox.ini

Fix UV_PYTHON_PREFERENCE reading breaks tox when env_site_packages_dir is in set_env

---

README.md

Fix readme table of contents

---

pyproject.toml
src/tox_uv/_venv.py
tox.ini

Fix crash when env already exists and has env_site_packages_dir in replacement

---

pyproject.toml
src/tox_uv/_run_lock.py
tests/test_tox_uv_lock.py

Until we get something better with https://github.com/astral-sh/uv/issues/11455

Force reinstall of wheel project for lock files 

---

README.md
src/tox_uv/_installer.py
src/tox_uv/_package.py
src/tox_uv/_package_types.py
src/tox_uv/_run.py
tests/test_tox_uv_package.py

refactor: delegate to uv's built-in packaging and dependency handling

---

README.md
src/tox_uv/_run_lock.py
tests/test_tox_uv_lock.py

fix: add option to avoid addition of --locked to uv sync
