tox-dev/tox-uv

- README.md
BTW amazing work on creating this so quickly after `uv` was released!
> Fix grammar and typos in README

- README.md
No need to tell people to explicitly install tox, it's already dependency of tox-uv:
https://github.com/tox-dev/tox-uv/blob/bd93a99698a48d694937f5cec1cdfd5c55ab149e/pyproject.toml#L40-L43
> README: tox is a dependency of tox-uv

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/workflows/check.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/tox_uv/_installer.py
- src/tox_uv/_venv.py
- tests/test_tox_uv_venv.py
- tox.ini
Furthermore, added templates for issues.
> Support major only Python environments and enable uv verbose mode on 2 or more -v for tox

- pyproject.toml
- src/tox_uv/_installer.py
- src/tox_uv/_venv.py
> Fixes for 0.1.6

- .github/workflows/check.yml
- src/tox_uv/_venv.py
Blocked on https://github.com/astral-sh/uv/issues/1539
> Support Windows

- src/tox_uv/_installer.py
- tests/test_tox_uv_api.py
The 'uv pip freeze' command should automatically determine whether or not to provide coloring if the output is going to a terminal or TTY with support. This is not happening in this case.
Ensuring color is always disabled for this command is a good first step to work around this issue. Fixes #38.
> Ensure uv pip freeze is colorless

- README.md
- src/tox_uv/_installer.py
- tests/test_tox_uv_installer.py
uv supports defining a custom resolution strategy, defaulting to 'highest', and allowing 'lowest' or 'lowest-direct' at the time of writing, which provides an alternative to package constraints enabling lowest direct or transitive dependencies to be installed.
This change provides a new `uv_resolution` configuration option for test environments, which if defined will apply the `--resolution` option to uv to enable this behavior.
Implements #28.
> Add uv_resolution as testenv parameter

- src/tox_uv/_venv.py
- tests/test_tox_uv_venv.py
Hi,
Thanks a lot for writing and maintaining tox-uv, as well as for all your work in the Python ecosystem!
Now, I have a somewhat unusual setup: a vendor-specific Python interpreter that is not in the normal search path. Since I'd like to use tox-uv to test that my modules will also be compatible with that version, I have a virtual environment with tox and tox-uv (and, actually, also test-stages for the tox-stages utility); however, a stock installation of tox-uv within such a virtual environment passes "-p 3.8" to uv, and since python3.8 is not in the search path, that fails.
What do you think about this change that uses sys.executable if the major and minor Python version are the same as the currently running interpreter?
Thanks in advance, and keep up the great work!
G'luck,
Peter
PS. …
> Pass sys.executable to `uv venv` if it is the same version

- .github/workflows/check.yml
- .github/workflows/release.yml
Hi! 
In the latest uv release, we no longer support this for using the system Python. You can see some more context at https://github.com/astral-sh/uv/issues/3765 and https://github.com/inventree/InvenTree/pull/7317.
> Drop use of `VIRTUAL_ENV=${Python_ROOT_DIR}` workaround

- README.md
- pyproject.toml
- src/tox_uv/_venv.py
- tests/test_tox_uv_venv.py
This PR enables the usage of the flag --python-preference to better control which Python interpreter is used.
See https://docs.astral.sh/uv/python-versions/#adjusting-python-version-preferences
It does so by exposing a `uv_python_preference` configuration field.
Note: this can be used to download missing Python interpreter. Use for example
```
[testenv]
uv_python_preference = only-managed
```
> Python preference

- .pre-commit-config.yaml
- pyproject.toml
- src/tox_uv/_venv.py
- tests/test_tox_uv_venv.py
- tests/test_version.py
- tox.ini
> Fix CI for new UV

- .github/ISSUE_TEMPLATE/config.yml
Redirect to tox-uv's discussion instead of tox.
Fix #86
> fix: discussion link

- tests/test_tox_uv_venv.py
The "python" executable exists only if "python3" exists, but "python3" can exist without "python".
This is at least the case in Fedora,
following https://peps.python.org/pep-0394/#for-python-runtime-distributors
> Tests: In other_interpreter_exe, try python3 -> python3.Y

- .github/workflows/check.yaml
- .pre-commit-config.yaml
- pyproject.toml
- src/tox_uv/_installer.py
- src/tox_uv/_run_lock.py
- src/tox_uv/_venv.py
- tests/test_tox_uv_lock.py
- tox.ini
This means that if you pass one -v to tox we show its output, if you pass two of it we make uv sync verbose.
> Drop 3.8 and uv sync now works in verbose mode same way as pip

- src/tox_uv/_installer.py
- src/tox_uv/_run_lock.py
- src/tox_uv/_venv.py
- tests/test_tox_uv_lock.py
> Fix verbosity flag also passed with single verbose flag to tox

- README.md
To run tox with plain virtualenv, I used to:
1. uninstall tox-uv
2. run tox
3. install tox-uv
That seemed tedious, so I looked up the correct way. I think this information might be useful to others.
> Document how to temporarily disable tox-uv

- src/tox_uv/_venv.py
- tests/test_tox_uv_venv.py
This resolves the following error that occurs when the tox environment is simply named `pypy`:
```
pypy: skipped because could not find python interpreter with spec(s): pypyNone
```
This was observed while testing [the uap-python project](https://github.com/ua-parser/uap-python/blob/3bd09b751a0a622b7f3ef8b977f10640d3d912ca/tox.ini#L3-L4).
It looks like a test case should be added to `test_tox_uv_venv.py`, but I had difficulty figuring out how to trigger the code branch. I would appreciate a pointer how to add a test case for this!
----
```ini
[tox]
env_list = pypy
[testenv]
skip_install = true
commands = python -V
```
```console
$ tox --version
4.23.2 from /home/kurt/.local/pipx/venvs/tox/lib/python3.13/site-packages/tox/__init__.py
registered plugins:
tox-uv-1.16.0 at …
```
> Fix `pypyNone` interpreter spec when major version unspecified

- tests/conftest.py
> Prevent user tox config from affecting tox-uv test runs

- src/tox_uv/_run_lock.py
- src/tox_uv/_venv.py
- tests/test_tox_uv_lock.py
Fixes: #110
Depends-On: https://github.com/tox-dev/tox-uv/pull/153
> Make sync prefer system python instead of uv managed

- pyproject.toml
- src/tox_uv/_venv.py
- tests/test_tox_uv_venv.py
Related: https://github.com/astral-sh/uv/issues/10686
> Display warning if PIP_CONSTRAINT(S) are defined and UV_CONSTRAINTS not

- src/tox_uv/_run_lock.py
- src/tox_uv/_venv.py
- tests/test_tox_uv_lock.py
This PR addresses an issue with `uv-venv-lock-runner`, in which the Python version in the created environment gets overwritten with whatever `uv` considers to be the "default" for the project, rather than the version specified in the tox definition. As the fix is straightforward, I opted to create a PR directly rather than reporting an issue.
Under the following tox config,
```
[tox]
envlist =
py{311,312}
[testenv]
runner = uv-venv-lock-runner
set_env =
py311: EXPECTED_MINOR_VERSION=11
py312: EXPECTED_MINOR_VERSION=12
commands =
python assert_correct_version.py
allowlist_externals =
python
```
```
import sys
import os
if __name__ == "__main__":
assert os.getenv("EXPECTED_MINOR_VERSION") == str(sys.version_info[1])
```
on a system with Python versions managed by pyenv and 3.11 set as …
> Use python version in lock runner

- src/tox_uv/_venv.py
- tests/test_tox_uv_venv.py
- Fixes issue where UV_CONSTRAINT warning was disabled even when
defined
- Avoids repeated messages on each environment_variables use
> Avoid false warnings about missing UV_CONSTRAINT variable

- pyproject.toml
- src/tox_uv/_run_lock.py
- src/tox_uv/plugin.py
- tests/test_tox_uv_lock.py
- tox.ini
> Allow skipping uv sync for lock runner via CLI flag

- .pre-commit-config.yaml
- src/tox_uv/_run_lock.py
- tests/test_tox_uv_lock.py
See https://github.com/astral-sh/uv/issues/11530#issuecomment-2660715025, we should fail if the `pyproject.toml` has been updated without regenerating the lock file, rather than ignore the change.
> Use --locked instead of --frozen for uv sync

- .github/workflows/check.yaml
- src/tox_uv/_venv.py
- tests/test_tox_uv_installer.py
- tests/test_tox_uv_venv.py
Due to the specific nature of how uv works, some minimal testing on Windows and MacOS would be needed.
Related: #193 #183
Related: https://github.com/astral-sh/uv/issues/14239
> Enable minimal testing with windows and macOS
